import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const pleaseSub = trpc.subscribe.sub.useQuery({ text: "Svenrisse" });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{pleaseSub.data?.pleaseSub}</div>
    </>
  );
};

export default Home;
